
# Autogenerated script for updating torsion parameters in a parmtop file using parmed. Do not modify. 

import os
from os import system
import subprocess
import shutil

def ParmedPrintDihedralsCLI(torsion_atom_names):
	return 'printDihedrals @%s @%s @%s @%s' % tuple(torsion_atom_names)

def ParmedDeleteDihedralCLI(torsion_atom_names):
	return 'deleteDihedral @%s @%s @%s @%s' % tuple(torsion_atom_names)

def ParmedAddDihedralCLI(torsion_atom_names, k, phase, per, scee, scnb):
	params=[float(k), float(per), float(phase),  float(scee), float(scnb)]
	return 'addDihedral @%s @%s @%s @%s %f %f %f %f %f' % (tuple(torsion_atom_names+params))

def UpdateParmTopCLI(prmtop_file_name, params, debug=True):

	parmed_buffer='parm %s\n' % (prmtop_file_name)

	if(debug):
		parmed_check_buffer='parm %s\n' % (prmtop_file_name)

	for key, value in params.items():
		torsion_atom_names=value['torsion_mask']
		if(debug):
			parmed_buffer+=ParmedPrintDihedralsCLI(torsion_atom_names)+'\n'
			parmed_check_buffer+=ParmedPrintDihedralsCLI(torsion_atom_names)+'\n'
		
		parmed_buffer+=ParmedDeleteDihedralCLI(torsion_atom_names)+'\n'
		parmed_buffer+=ParmedAddDihedralCLI(torsion_atom_names, value['height'], value['phase'], value['periodicity'], value['scee'], value['scnb'])+'\n'

	parmed_buffer+='outparm %s.new\n' % (prmtop_file_name)

	if(debug):
		print(parmed_buffer)

	command=['parmed']
	result = subprocess.run(command, input=parmed_buffer, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

	system('mv %s %s.bak' % (prmtop_file_name, prmtop_file_name))
	system('mv %s.new %s' % (prmtop_file_name, prmtop_file_name))

	if(debug):
		result = subprocess.run(command, input=parmed_check_buffer, text=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
		print(result.stdout)

	return
	
def UpdateParmTopInMemory(prmtop_file_name, params, debug=True, stdout=True, round_periodicity=False):
    """
    Update torsion parameters in an AMBER prmtop using ParmEd's Python actions API (4.x compatible).
    Avoids spawning the external 'parmed' binary and minimizes I/O.

    Supports both single-primitive and multi-primitive dihedrals:

    Single-primitive (backward compatible):
        params = {
            "torsion_label": {
                "torsion_mask": ["A", "B", "C", "D"],
                "height": 1.5,              # scalar
                "phase": 0.0,               # scalar
                "periodicity": 2,           # scalar
                "scee": 1.2,
                "scnb": 2.0
            }
        }

    Multi-primitive (NEW):
        params = {
            "torsion_label": {
                "torsion_mask": ["A", "B", "C", "D"],
                "height": [1.5, 0.8, 0.3],        # list of 3 primitives
                "phase": [0.0, 180.0, 0.0],       # list of 3 primitives
                "periodicity": [1, 2, 3],         # list of 3 primitives
                "scee": [1.2, 1.2, 1.2],          # list (or scalar, will broadcast)
                "scnb": [2.0, 2.0, 2.0]           # list (or scalar, will broadcast)
            }
        }
    """
    import parmed as pmd
    from parmed.tools import actions as pactions

    # ---------- helpers ----------
    def _coerce_primitive_lists(val):
        """
        Returns list of tuples: [(height, phase, periodicity, scee, scnb), ...]
        Handles both single primitive (scalars) and multi-primitive (lists).
        """
        if isinstance(val, dict):
            need = ("height","phase","periodicity","scee","scnb")
            if not all(k in val for k in need):
                missing = [k for k in need if k not in val]
                raise ValueError(f"Missing keys in params value: {missing}")

            # Helper: convert scalar or list to list
            def to_list(x):
                if isinstance(x, (list, tuple)):
                    return list(x)
                else:
                    return [x]

            # Convert all to lists
            heights = [float(h) for h in to_list(val["height"])]
            phases = [float(p) for p in to_list(val["phase"])]
            periodicities = [float(p) for p in to_list(val["periodicity"])]
            scees = [float(s) for s in to_list(val["scee"])]
            scnbs = [float(s) for s in to_list(val["scnb"])]

            # Determine number of primitives (from longest list, usually height)
            n_prims = max(len(heights), len(phases), len(periodicities))

            # Broadcast scalars if needed (e.g., scee=1.2 for all primitives)
            if len(scees) == 1 and n_prims > 1:
                scees = scees * n_prims
            if len(scnbs) == 1 and n_prims > 1:
                scnbs = scnbs * n_prims

            # Validate all lists have same length
            if not all(len(x) == n_prims for x in [heights, phases, periodicities, scees, scnbs]):
                raise ValueError(
                    f"All parameter lists must have same length (n_prims={n_prims}):\n"
                    f"  heights: {len(heights)}, phases: {len(phases)}, "
                    f"periodicities: {len(periodicities)}, scees: {len(scees)}, scnbs: {len(scnbs)}"
                )

            # Return list of tuples in order: (height, periodicity, phase, scee, scnb)
            # This matches the unpacking order: (H, PER, PH, SCEE, SCNB)
            return list(zip(heights, periodicities, phases, scees, scnbs))

        elif isinstance(val, (list, tuple)) and len(val) >= 5:
            # Old format: single tuple [height, phase, periodicity, scee, scnb]
            # But we need to return (height, periodicity, phase, scee, scnb) to match unpacking
            return [(float(val[0]), float(val[2]), float(val[1]), float(val[3]), float(val[4]))]
        else:
            raise ValueError(f"Unsupported parameter value: {val!r}")

    def _mask_from_value(key, val):
        if isinstance(val, dict) and "torsion_mask" in val:
            m = val["torsion_mask"]
        else:
            raise ValueError(f"params['{key}'] must contain a 4-item 'torsion_mask' list of atom labels.")
        if not (isinstance(m, (list, tuple)) and len(m) == 4):
            raise ValueError(f"Invalid torsion_mask for {key}: {m}")
        return [str(x) for x in m]

    def _resolve_action(*names):
        for n in names:
            cls = getattr(pactions, n, None)
            if cls is not None:
                return cls
        raise ImportError(f"None of the action names {names} exist in parmed.tools.actions")
    # --------------------------------

    # Load topology directly using parmed
    parm = pmd.load_file(prmtop_file_name)

    # Get residue name (use first residue, assuming single-molecule system)
    # This is critical for proper atom selection in multi-residue systems
    if len(parm.residues) > 0:
        residue_name = parm.residues[0].name
    else:
        residue_name = "MOL"  # Default fallback

    if debug:
        print(f"\nDetected residue name: {residue_name}")

    # Resolve 4.x action classes (handles minor naming differences across builds)
    OutParm  = _resolve_action("outparm", "parmout", "ParmOut")
    PrintDih = _resolve_action("printDihedrals", "PrintDihedrals")
    DelDih   = _resolve_action("deleteDihedral", "deleteDihedrals", "DeleteDihedrals")
    AddDih   = _resolve_action("addDihedral", "addDihedrals", "AddDihedrals")

    # Apply edits
    for key, val in params.items():
        # Use residue-qualified masks (like ffpopt does) for proper atom selection
        atom_names = _mask_from_value(key, val)
        a1, a2, a3, a4 = [f":{residue_name}@{x}" for x in atom_names]
        primitives = _coerce_primitive_lists(val)

        if debug:
            print(f"\nProcessing torsion: {key}")
            print(f"  Atom masks: {a1} {a2} {a3} {a4}")
            print(f"  Number of primitives: {len(primitives)}")
            PrintDih(parm, a1, a2, a3, a4).execute()

        # Delete ALL existing dihedrals for this atom type
        DelDih(parm, a1, a2, a3, a4).execute()

        # Add each primitive (multi-primitive = multiple AddDih calls for same torsion)
        for i, (H, PER, PH, SCEE, SCNB) in enumerate(primitives):
            if round_periodicity:
                PER = int(round(PER))
            else:
                PER = float(PER)  # keep fractional periodicity

            # Add this primitive to prmtop
            # AddDih signature: mask1, mask2, mask3, mask4, phi_k, per, phase, scnb, scee
            # Our variables: H=barrier(phi_k), PER=periodicity(per), PH=phase, SCNB, SCEE
            AddDih(parm, a1, a2, a3, a4, H, PER, PH, SCNB, SCEE).execute()

            if debug:
                print(f"    Primitive {i+1}/{len(primitives)}: H={H:.4f}, PH={PH:.2f}°, PER={PER}, SCEE={SCEE:.2f}, SCNB={SCNB:.2f}")

    # Write to tmp and atomically replace
    tmp_out = f"{prmtop_file_name}.new"
    OutParm(parm, tmp_out).execute()

    if os.path.exists(f"{prmtop_file_name}.bak"):
        os.remove(f"{prmtop_file_name}.bak")
    if os.path.exists(prmtop_file_name):
        shutil.move(prmtop_file_name, f"{prmtop_file_name}.bak")
    shutil.move(tmp_out, prmtop_file_name)

    # Optional verification
    if debug:
        print("\n=== Verification: Updated dihedrals ===")
        parm_updated = pmd.load_file(prmtop_file_name)
        for key, val in params.items():
            atom_names = _mask_from_value(key, val)
            a1, a2, a3, a4 = [f":{residue_name}@{x}" for x in atom_names]
            print(f"\nFinal dihedrals for {key}:")
            PrintDih(parm_updated, a1, a2, a3, a4).execute()

    return parm

def CreatePrmtopWithoutTorsions(original_prmtop, output_prmtop, torsion_masks, debug=False):
    """
    Create a modified prmtop with specified torsions deleted.

    This is used for linear initial guess computation (ffpopt-style approach):
    - Load original prmtop
    - Delete specified torsions
    - Save to output_prmtop
    - Returns path to new prmtop

    Args:
        original_prmtop: Path to original prmtop file
        output_prmtop: Path for output prmtop (without torsions)
        torsion_masks: List of torsion masks, e.g., [["C1","C2","C3","C4"], ...]
        debug: If True, print details

    Returns:
        str: Path to output prmtop file

    Example:
        CreatePrmtopWithoutTorsions(
            "prmtop",
            "prmtop_no_torsion",
            [["C1","C2","C3","C4"], ["C2","C3","C4","C5"]]
        )
    """
    import parmed as pmd
    from parmed.tools import actions as pactions

    def _resolve_action(*names):
        for n in names:
            cls = getattr(pactions, n, None)
            if cls is not None:
                return cls
        raise ImportError(f"None of the action names {names} exist in parmed.tools.actions")

    # Load topology
    parm = pmd.load_file(original_prmtop)

    # Get residue name
    if len(parm.residues) > 0:
        residue_name = parm.residues[0].name
    else:
        residue_name = "MOL"

    if debug:
        print(f"\nCreating prmtop without torsions")
        print(f"  Original: {original_prmtop}")
        print(f"  Output: {output_prmtop}")
        print(f"  Residue: {residue_name}")
        print(f"  Deleting {len(torsion_masks)} torsion(s)")

    # Resolve actions
    DelDih = _resolve_action("deleteDihedral", "deleteDihedrals", "DeleteDihedrals")
    OutParm = _resolve_action("outparm", "parmout", "ParmOut")

    if debug:
        PrintDih = _resolve_action("printDihedrals", "PrintDihedrals")

    # Delete each torsion
    for i, atom_names in enumerate(torsion_masks):
        if len(atom_names) != 4:
            raise ValueError(f"Torsion mask must have 4 atoms, got {len(atom_names)}: {atom_names}")

        a1, a2, a3, a4 = [f":{residue_name}@{x}" for x in atom_names]

        if debug:
            print(f"\n  Torsion {i+1}: {atom_names}")
            print(f"    Before deletion:")
            PrintDih(parm, a1, a2, a3, a4).execute()

        # Delete this torsion
        DelDih(parm, a1, a2, a3, a4).execute()

        if debug:
            print(f"    After deletion:")
            PrintDih(parm, a1, a2, a3, a4).execute()

    # Save modified prmtop
    OutParm(parm, output_prmtop).execute()

    if debug:
        print(f"\nSaved prmtop without torsions to: {output_prmtop}")

    return output_prmtop

